### PR TITLE
Missed some

### PR DESCRIPTION
**Pull request by k4n30**
more :)

### CODE REVIEW

**Comment by dmustanger** [comment]
yes I know I do not have all the soda and food. this is why they are just logging still. But really what cheater is going to spawn just soda and food lol?

**Comment by k4n30** [comment]
Whitelisted some more items for you so they don't log

**Comment by icomrade** [comment]
Logging the amount of zeds deleted by a player is useful, e.g. if you see a very large block of zeds get deleted in under 2 seconds then it's safe to assume the player is using a zombie shield.

**Comment by k4n30** [comment]
More than half of them are already whitelisted so why not do them all or none at all?

**Comment by dmustanger** [comment]
i have all the zeds just waiting for him to push some commits so there arent any conflicts with merging.

**Pull request closed without merging**
