### PR TITLE
Updated addmagazinecargo.txt

### PR DESCRIPTION
**Pull request by dmustanger**
A more practical use of this filter. Instead of banning single items,
ban everything and filter what you want to allow.
Also Removed weapons from this file as they belong in the addweaponcargo.txt.

### CODE REVIEW

**Comment by facoptere** [comment]
Are you sure you tested it on a production server? 

There is a reason why I keep both the white list and the black list.

**Comment by dmustanger** [comment]
Yes. I have not had anything show up in my log for over a week now. You dont even have to pick the items up to get them to show up in the log. They show in the log as they spawn in. I still dont have all empty cans, soda and food as this is why they are still set to 1. I always get one that still pops up every once in a while. Small chance to spawn?

**Comment by icomrade** [comment]
00Rnd_ will be also filtered by 0Rnd_ which means that a player will get kicked for 100 rnd or 200 rnd mags because it is not exclude from the 0Rnd_ restriction.

**Comment by facoptere** [comment]
My concern is players from 1.7.7 or earlier, who have old item on their magazine cargo. I mean "old" = that does not spawn in 1.7.7.1 anymore. If you can state that they won't be kicked it's fine.

Second problem is that this white list is automatically generated by a script that preprocesses and scans the source code, and you edited it manually. When 1.7.7.2 is out you will have to edit it again.

**Comment by facoptere** [comment]
@icomrade : rule is 
"0Rnd_" !"00Rnd_" 
so 00Rnd_ is excluded from 0Rnd_ line.

**Comment by dmustanger** [comment]
to make it work with older versions of dayz i will have to add an exception for the as50 mag and m107 mag. if you go really older version the m136? other then that it would be the same.

for 1.7.7.2 as far as i can tell they are just removing the trash?

from the dayz forums
" [UPDATED] - Removed all trash items from building loot tables and replaced with a generic table (better organisation) "

but i plan to update it anyways for my server. if need be we can set everything to 1 when that time comes.

**Comment by facoptere** [comment]
They removed crafting items (bluprints, weapon options) from config.cpp too.
config.cpp is much cleaner than 1771

**Comment by facoptere** [comment]
I pushed in production and immediately 2 players complained.
1 user is complaining on the forum: http://dayzmod.com/forum/index.php?/topic/103204-fr-34-fr-129-raid-wine-servers-thread/page__st__280#entry1396417

I don't think it's fully tested.

PS: oops, it's only on my server. maybe it's an error on my side.

**Comment by dmustanger** [comment]
he said "Addweaponcargo" kick. i haven't changed that yet but i am working on it also

**Pull request merged**
